[tool.poetry]
name = "novaposhta-api-client"
version = "0.1.0"
description = "Python client for Nova Poshta API"
authors = ["Oleksii <semolex@live.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.25.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
black = "^23.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
